import { randomUUID } from 'node:crypto';
import { setTimeout as delay } from 'node:timers/promises';

import { Injectable } from '@nestjs/common';

import { logger } from '../common/logger.js';
import { ProductsRepository } from '../source/products.repository.js';

const PIPELINE = 'simulation';
const UPDATE_EVERY = 3;
const DELETE_EVERY = 5;
const MILLISECONDS_PER_SECOND = 1000;

export interface MutationRequest {
  readonly count: number;
  readonly ratePerSecond: number;
}

export interface MutationSummary {
  readonly created: number;
  readonly updated: number;
  readonly deleted: number;
  readonly elapsedSeconds: number;
}

@Injectable()
export class SimulationService {
  constructor(private readonly products: ProductsRepository) {}

  async generateMutations(request: MutationRequest): Promise<MutationSummary> {
    const batchId = randomUUID().slice(0, 8);
    const startedAt = Date.now();
    let created = 0;
    let updated = 0;
    let deleted = 0;

    for (let index = 0; index < request.count; index += 1) {
      const product = await this.products.create({
        sku: `SIM-${batchId}-${String(index)}`,
        name: `Simulated product ${String(index)}`,
        description: 'generated by /admin/simulate/mutations',
        price: Number((index % 100) + 0.99),
        status: 'active',
      });
      created += 1;

      if (index % UPDATE_EVERY === 1) {
        await this.products.update(product.id, { name: `${product.name} (revised)` });
        updated += 1;
      }
      if (index % DELETE_EVERY === 4) {
        await this.products.softDelete(product.id);
        deleted += 1;
      }

      await this.#pace(index, startedAt, request.ratePerSecond);
    }

    const elapsedSeconds = Number(((Date.now() - startedAt) / MILLISECONDS_PER_SECOND).toFixed(2));
    logger.info(
      { pipeline: PIPELINE, created, updated, deleted, elapsedSeconds },
      'mutations generated',
    );

    return { created, updated, deleted, elapsedSeconds };
  }

  async #pace(index: number, startedAt: number, ratePerSecond: number): Promise<void> {
    const targetElapsed = ((index + 1) * MILLISECONDS_PER_SECOND) / ratePerSecond;
    const remaining = targetElapsed - (Date.now() - startedAt);

    if (remaining > 0) {
      await delay(remaining);
    }
  }
}
